### ISSUE TITLE
Realtime Clinical Dashboards

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/elcid.openhealthcare.org.uk#7]

**Comment by davidmiller** [comment]
Dashboards of Key performance indicators in real time

**Comment by michaeledwardmarks** [comment]
@gabpoll might know what some of the key targets are.
As i recall they include
MRSA Bacteraemia
C.diff infections etc

**Comment by GabPoll** [comment]
The target numbers keep changing, but key indicators
- MRSA bacteraemia - which means number of blood cultures with MRSA in it - this is a special type of Staph aureus
- MSSA bacteraemia - blood cultures with MSSA in it (the standard type of Staph aureus
- E coli bacteraemia - blood cultures with E. coli in it
- C difficile toxin infection - stool results with C diff toxin positive
- CRO infections - this is not currently defined on elCID but we should absolutely put this together. Not easy though and will need stakeholder discussion - in essence these are multi-antibiotic resistant superbugs. Genuine nightmare - essentially pre-antibiotic era infections. Everyone is worried about them or will be soon http://en.wikipedia.org/wiki/Carbapenem-resistant_enterobacteriaceae
